### ISSUE TITLE
Alternative Download source

### ISSUE THREAD

**Issue by IzzySoft** [amit-bhandari/AB-Music-Player#11]
With the app being open source, would you mind providing an alternative download source of the `.apk` – e.g. via Github `releases/` (see [Creating Releases](https://help.github.com/articles/creating-releases/) in the Github help)?

**Comment by amit-bhandari** [comment]
Thanks for the suggestion. I have created the release. Let me know if I missed anything in it.

**Comment by IzzySoft** [comment]
Thanks! Just a suggestion for the package info/manifest:

    package: name='com.bhandari.music' versionCode='145' versionName='Version 8' platformBuildVersionName=''

`versionName` usually is the app version in "human readable format", and rather should not contain any white-spaces. So here, instead of "Version 8", e.g. "8.0" would be better fitting. Maybe you want to consider that for future releases?

And btw: what license are you using for the app? Further I wonder how "offline" goes together with Firebase :wink:

I've just added your app to [my repo](https://apt.izzysoft.de/fdroid/repo), so you can [find it here](https://apt.izzysoft.de/fdroid/index/apk/com.bhandari.music). Hope the entry fits you. Let me know if I shall update something in the description.

**Comment by amit-bhandari** [comment]
Yes sure, I will consider it for next release.

I am not sure about what license I have to use for it, little noobness in that area. Will have to research. Will be helpful if you could give some insight about that.

And thank you for adding my app to your repository. It means so much to me. :+1:  :)

**Comment by IzzySoft** [comment]
Thanks again!

As for the license: this often is a "personal thing". For my software projects, I usually take GPLv2 (very abstract description: free to use, free to re-use the code but only under the same license, free to spread it as long as no money is taken for it) as I want it to be available to everybody for free – but nobody should cash it. If you don't care about your code being used commercially as long as you're credited as the author, Apache license is often used. Other frequently used licenses include MIT and BSD. Hard to say which license you should take … But maybe [Choose a License: Choose an open source license](https://choosealicense.com/) can help you?

* for a closer look: [alphabetical list of open source licenses](https://opensource.org/licenses/alphabetical)
* [OSS Watch license differentiator](http://oss-watch.ac.uk/apps/licdiff/): asks you a few questions, and then should come up with a choice of matching licenses

There are probably many more sites on that topic. I'd suggest starting with the last link.

**Comment by amit-bhandari** [comment]
Great resources. Thanks. Will go through them on weekend and will decide on something.

**Comment by IzzySoft** [comment]
Please let me know when you've decided, so I can update the record in my repo to reflect that :wink:

**Comment by amit-bhandari** [comment]
Sure man

**Comment by amit-bhandari** [comment]
I have updated code with Apache license. 
And I am curious as to why you have maintained that repository of f-Droid. Just curious. And why do you think my app deserve to be in that repo?

**Comment by IzzySoft** [comment]
> I have updated code with Apache license.

Thanks! Adjusted the Metadata in my repo. Should be reflected there with the next sync (todays sync was just completed, so latest tomorrow evening).

> And I am curious as to why you have maintained that repository of f-Droid.

I'm an open-source and privacy advocate – and thus very much prefer F-Droid above Playstore, Amazon etc. First because you can use their repo "anonymously" (without an account) – and second because they have very strict rules, so using F-Droid I'd consider safer than any other place. But "very strict" also means not all open source apps make it there, mostly for proprietary components (as in your case Firebase, GMS and Google Ads). That's where my repo shall jump in: still fulfilling the "anonymous usage" part, but being less strict.

Often my repo serves as a "stepping stone", until developers manage to get rid of those proprietary elements and get listed in the official F-Droid repo. Some apps never manage that for one reason or the other, so they stay with me. Still, users get an additional source of apps which are kept up-to-date "automatically".

> And why do you think my app deserve to be in that repo?

It's free, open-source, and users gave it a good rating. So I want to make it available to those not using Playstore. Admitted, I've not tried it myself (I rarely listen to music via my Android devices), but it left a good impression so far :wink:

Of course, if I could convince you to drop the proprietary elements from your app, or at least have a "free flavor" (if that's possible once you've started with Firebase), I'd happily assist you to get your app into the official repo.

**Comment by amit-bhandari** [comment]
Thanks for the info. Never gave a try to f-Droid. Will soon look into it as well.

As far as making free flavour of AB Music. I could get rid of ads and google sign in but removing firebase is difficult as Lyric cards functionality is totally based on that.

**Comment by amit-bhandari** [comment]
> I'm an open-source and privacy advocate

Is this your job?

**Comment by IzzySoft** [comment]
I was afraid it won't be easy getting rid of Firebase – but with Firebase in, your app won't be accepted at F-Droid. If you'd create a version without the other proprietary elements and attach that to your releases (either instead the current one, or with a specific name element I could match upon), I'd gladly pick that for my repo (instead of the current one), while you could still have the "full variant" on Playstore.

And as much as I wish that would be a job that paid, "open-source and privacy advocate" is rather a description of my "mind state" :wink:

**Comment by amit-bhandari** [comment]
I think it would be better if I create different repo for that version. 

Removing everything related to google from that version.

**Comment by amit-bhandari** [comment]
> And as much as I wish that would be a job that paid, "open-source and privacy advocate" is rather a description of my "mind state" wink

haha :100:

**Comment by IzzySoft** [comment]
> I think it would be better if I create different repo for that version.

Usually such is done using gradle flavors, especially if all other code is shared. But if you chose the way via a separate repo, let me know to check that once an APK is available there.

**Comment by amit-bhandari** [comment]
Yeah. Sure. I will definitely think about it.
